---
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

cache:
  directories:
    - "${HOME}/.composer/cache"
    - "${HOME}/.npm/"
env:
  global:
    - PATH="${HOME}/bin:${PATH}"

matrix:
  include:
    - php: 7.4snapshot
      allow_failures: true
    - php: 7.3
      env: SNIFF=1
    - php: 5.5
      # As the latest Debian does not support PHP 5.5 anymore, we need to force using 'trusty'.
      dist: trusty
    - php: 5.4
      # As the latest Debian does not support PHP 5.4 anymore, we need to force using 'trusty'.
      dist: trusty
    - php: 5.3
      # As the latest Debian does not support PHP 5.3 anymore, we need to force using 'precise'.
      dist: precise

  fast_finish: true

before_install:
  - npm set loglevel error
  - npm set progress false

install:
  - npm install -g jsonlint

script:
  - if [[ "$SNIFF" == "1" ]];then find . -type f -name "*.json" -print0 | xargs -0 -n1 jsonlint -q; fi
  - if [[ "$SNIFF" == "1" ]];then find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l; fi
  - if [[ "$SNIFF" == "1" ]];then composer validate; fi
  - travis_wait composer install --no-interaction --no-progress --no-scripts --no-suggest --optimize-autoloader --prefer-dist --verbose
  - composer install-codestandards
  - ./vendor/bin/phpcs -i
  - ./vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion "${TRAVIS_PHP_VERSION:0:3}" --exclude=PHPCompatibility.Upgrade.LowPHP ./src/
  - if [[ "$SNIFF" == "1" ]];then ./vendor/bin/security-checker -n security:check --end-point=http://security.symfony.com/check_lock; fi
